FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Pokemon.sln", "./"]
COPY ["apps/UserApi/UserApi.csproj", "apps/UserApi/"]
COPY ["src/Users/Users.csproj", "src/Users/"]
COPY ["tests/UsersTest/UsersTest.csproj", "tests/UsersTest/"]

RUN dotnet restore "src/Users/Users.csproj"
RUN dotnet restore "apps/UserApi/UserApi.csproj"
RUN dotnet restore "tests/UsersTest/UsersTest.csproj"
COPY . .

WORKDIR "/src/apps/UserApi"
RUN dotnet build -c Release -o /app

WORKDIR "/src/tests/UsersTest"
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/runtime:6.0 AS testing
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "UsersTest.dll"]

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "UserApi.dll"]