FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Pokemon.sln", "./"]
COPY ["apps/PokemonApi/PokemonApi.csproj", "apps/PokemonApi/"]
COPY ["src/Pokemon/Pokemon.csproj", "src/Pokemon/"]
COPY ["src/Shared/Shared.csproj", "src/Shared/"]
COPY ["apps/PokemonConsole/PokemonConsole.csproj", "apps/PokemonConsole/"]

RUN dotnet restore "src/Shared/Shared.csproj"
RUN dotnet restore "src/Pokemon/Pokemon.csproj"
RUN dotnet restore "apps/PokemonApi/PokemonApi.csproj"
RUN dotnet restore "apps/PokemonConsole/PokemonConsole.csproj"
COPY . .

WORKDIR "/src/apps/PokemonApi"
RUN dotnet build -c Release -o /app

WORKDIR "/src/apps/PokemonConsole"
RUN dotnet build -c Release -o /app

FROM build AS publish
RUN dotnet publish -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "PokemonApi.dll"]